apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBQbHF4FvUAwA35wdmw5OjX1jXpLEi8dkh+wTYAOadYro1BGzIICrwCG8K+9h3e5/zI+u2SUQ/tPSPvpvLGgW/lVJ0n952KPv0/b5WxHH2muc5hed+yKlSdqpscMVg71dis7sptkbOxWQUaqKezkGKCtdQVKNEmKWHS+CbSj1ZW2Vde5NuKzQTC39tROC1zwDXVAj6mFxfboGWt0a7rEHPvw3k1CsC0XXti6D1KZLGRGsjAeQkBaU4EjXVor9jPdN/ougj9xWBh8Zwj30KqBRvYpIN2toMi47gtv+cmItPeu9lcBs9feQbk7N8Dh2JVum9MDVq+ABTBAoeKGVINZePQtabzWpbPZu6s4ccC/+ZzyhHJh8AwubOYPxlAWuOx2n87dIGYfx8uRKv12Seb8b8wLkf1Fg6SJY0GbRoo+uuWhsl39EBkQS61fyj084ECjDfbpcIYDz6oTP418qhqSWxXefcKT3BO8ntR349l6lcZJ5uxtystLI4UDNbTRnS2k/h8J1NkbYWXliZoLsXb82T7D6FM9I+dkgFeReesNaFf7JbNmxTf+H9pEWzYtL/T/MW5poBm31fpI/syUQUCjZVb0Mx5bLsgAM+we3d/1VsstaQ9/HZrpHTsm1qHQp56tWCrO9i3cOXsBwowZDn28ByujS4ghFgRgtoc0bl8CXzuEdAB6dJme0K0G3pDWFGQyFM4BadJKKYEwnEqezggyFQ/992p9+jGkDaoDqwhZE91aJRr1BUXoNQz
    username: AgBOuOEj29WQick5k4FbEn0jyz0D7YB2tR7AhWeYJCNdzdvQgRhQ4dPEuw2TGlFwlPdnCvnZn8tk47dg6GmXIcB1IPq1M0qmQnM/uB5MlL4QThO2ZVgxhTqIDR86OR9hAeQ5ujgiIoIiRzTXTpVxxIcRxiNkfug6TeUUtKL1yWc0dZA9gyIijrv/FRB263CyxVRRzcQc+QMNUTepippsks66Mi5m/WJUqRNXk7/454rUAzQP/MQMx91MP9vbBVXYdrz7AbQmgtci7NSabv1F6IXUM1qPYEQa2kyiKk+DYzFGMIa/69Z3hZ1OCOJS2iwt7kKtj0wdvfObzye+QhTgD83sf+URknikmLge2IMRNZT9VlF1hcRkavqHiSykiAI6T0i1h/J378C9/KSUxqYZakv84NhbMm2x2ygoxqqLZmVxY0diC33eygsoECvfKPXqHc41jcexarVMqTu6n4TmvptNCqxuEnvid0aiE+sYPU70pZRdCpNFvs1MyW5nBoTNQjAHA2nYE07SqXtHMqi2CtdNhcX0IGnQ58iEWzZKvnbpDXy6Yioj304Nej3jgednKHw9PKkUhblk64v+dM4UZwRtz614SfhJwaJCCEbAZt0QiBcdUbY/XFhaOmk1R2UCkQqsnLxBxZ3K5s3OmEbzKAsgsvFnOqLqWF5RnIamBAZ3aSWKC0Jl/bDJs8HtIaQAN/hA90yBTaQ/Dkb+hYEDn5ATiCu7O0o9XdE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

